# Site
repository: maxqyzhu/Homepage
# favicon: images/favicon.ico

# Personal info
name: Zhu Qiuyu
title: P.h.d. Student in NUS
email: qiuyu_zhu@u.nus.edu
website: maxqyzhu.github.io

# Social links
# twitter_username: maxqyzhu
github_username:  maxqyzhu
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: dvalinn1993
linkedin_username: qiuyu-zhu-599064157
# pinterest_username: jekyll
# youtube_username: maxqyzhu
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Qiuyu and I'm a PhD student from National University of Singapore. My research interest is: Machine Learning, Supply Chain Management, Statistics and Information Theory.

  Email: <a href="mailto:{{ site.email }}" target="_blank">{{ site.email | escape }}</a>
  
  Skills: <mark>Probability</mark>, Statistics, <mark>R</mark>, Python, Matlab, C#, Unity

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in operations research and machine learning, some of my other interests and hobbies are:
   - Badminton
   - Gaming
   - Board Game

# Footer
footer_show_references: true

# Build settings
remote_theme:  maxqyzhu/my_web

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
